name: Docker image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    #nic

    # -
    #   name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2
    # -
    #   name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: suchencjusz
        password: 5fd64b6e-da62-43d5-bbb2-8024e1126185


    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: suchencjusz/menel.me

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # -
    #   name: Build and push
    #   uses: docker/build-push-action@v3
    #   with:
    #     push: true
    #     tags: user/app:latest
